#!/usr/bin/env bash
# Copyright (c) 2013-2106 All Right Reserved  Alec Clews
#
# author: Alec Clews
# alecclews@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#
# NB These Scripts support Pi Raspian (Debian)

echo About to clone the latest script from CCHS Pi setup.

git clone https://github.com/alecthegeek/CCHS_Raspian_for_IoT.git ~/CCHS_Raspian_for_IoT

cd ~/CCHS_Raspian_for_IoT

for branch in `git branch -a | grep remotes | grep -v HEAD | grep -v master `; do
    git branch --track ${branch#remotes/origin/} $branch
done

OPS3=$PS3

echo There are multiple versions of these sripts. Please select the one you want to use
PS3='If you not sure just choose "master" '

select br in $(git branch|sed -e '/^\*\? \? /s///'); do
  git checkout $br &&
    break
done

export LOC=$PWD

PS3=$OPS3

./runme1st
echo $LOC/runme2nd >> ~/.profile
sudo touch /forcefsck
sudo init 6

