#!/usr/bin/env bash
# Copyright (c) 2013 All Right Reserved  Alec Clews
#
# author: Alec Clews
# alecclews@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#


ask() {
  read -p "$1" -r < /dev/tty
  echo $REPLY
}

# Install a few dev tools
sudo apt-get -y install vim git git-gui git-doc git-svn subversion screen tmux ack-grep emacs locate


if [[ $(ask "Do you wish to install MineCraft for Pi? [y/N] ") =~ ^[Yy]$ ]]; then

  minecraft=0.1.1   # Modify to lastest
  wget https://s3.amazonaws.com/assets.minecraft.net/pi/minecraft-pi-$minecraft.tar.gz

  [[ -d /usr/local/mcpi ]] && sudo rm -rf /usr/local/mcpi
  sudo tar -xvzpf minecraft-pi-$minecraft.tar.gz -C /usr/local

  echo  '# Setup for Minecraft Python API' | sudo tee /etc/profile.d/minecraft-py.sh 

  if [[ -n "$PYTHONPATH" ]] ; then
    echo 'PYTHONPATH=$PYTHONPATH:/usr/local/mcpi/api/python/mcpi' | sudo -a tee /etc/profile.d/minecraft-py.sh
  else
    echo 'PYTHONPATH=/usr/local/mcpi/api/python/mcpi' | sudo tee -a /etc/profile.d/minecraft-py.sh
  fi
  
  /usr/local/mcpi/api/python/mcpi

  echo 'export PYTHONPATH' | sudo tee -a /etc/profile.d/minecraft-py.sh

  cat <<'EOF'  | sudo tee /usr/local/bin/minecraft
#!/bin/sh
/usr/local/mcpi/minecraft-pi > /dev/null 2>&1 &
EOF

  sudo chmod a+x /usr/local/bin/minecraft

  echo Minecraft has been installed as minecraft. Please login in again to use the Python API.

  if [[ $(ask "Do you wish to install Java SDK to run the Java demo for Minecraft? [y/N] ") =~ ^[Yy]$ ]] ; then
    sudo apt-get -y install oracle-java7-jdk
    echo "Set the class path to /usr/local/mcpi/api/java/lib/McPi.jar"
  fi
fi
