#!/usr/bin/env bash

# From the instructions at
# http://dave.cheney.net/2015/09/04/building-go-1-5-on-the-raspberry-pi
# Thanks to @davecheney

#  Runing:

# 1) Will attempt to use the already installed version of Go if possible
# 2) Default is to install/upgrade to version 1.5 -- but you can supply an alternative version of you wish
# 3) After building the new version, the tool chain is rebuild again using the new compiler before install

INSTALL_VERSION=${1:-1.6.2}
OS=linux
ARCH=armv6l

if type go > /dev/null 2>&1 && [[ "$(go version 2>/dev/null)" =~ $INSTALL_VERSION ]] ;then
  echo $(go version)  already installed at $(go env GOROOT)
  exit 2
fi

[ -d /usr/local/go ] && sudo rm -rf /usr/local/go
 
wget -O -  https://storage.googleapis.com/golang/go${INSTALL_VERSION}.${OS}-${ARCH}.tar.gz | sduo tar -xzC /usr/local  -f -


echo '# Setup for golang' |sudo tee /etc/profile.d/golang.sh  > /dev/null
echo 'PATH=$PATH:/usr/local/go/bin'|sudo tee -a /etc/profile.d/golang.sh > /dev/null

source /etc/profile.d/golang.sh

echo Now installing the Go tools

sudo -i GOPATH=/tmp GOBIN=$(go env GOROOT)/bin go get -u golang.org/x/tools/cmd/...

echo $(go version) installed

