#!/usr/bin/env bash
# Copyright (c) 2013 All Right Reserved  Alec Clews
#
# author: Alec Clews
# alecclews@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#
#    Special thanks to @mikered for wifi set up code

export UPDATE_LABEL="Updated_$(date +%F)"
export LOG_FILE="/home/$USER/$UPDATE_LABEL.log"
function eLog { # Echo & log input
  echo "$1" | tee -a $LOG_FILE 2>&1
}
function execLog { # Execute & log output
  $@ | tee -a $LOG_FILE 2>&1
}
eLog "CCHS update script: runme2nd"
eLog "Logging to: $LOG_FILE"

# Add Check to encourage users to keep system up to date
eLog "__ Update Check____________________________________________________"
echo 'APT::Update::Post-Invoke-Success {"touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true";};' | \
				sudo tee -a /etc/apt/apt.conf.d/15update-stamp > /dev/null

# Set initial check to every 7 days

echo '# Check apt-get is run every few days' |sudo tee /etc/profile.d/checkUpgrade.sh
echo 'no_of_days=7' |sudo tee -a /etc/profile.d/checkUpgrade.sh
echo 'no_of_seconds=$(($no_of_days*24*60*60))' |sudo tee -a /etc/profile.d/checkUpgrade.sh
echo 'if [[  ! -e /var/lib/apt/periodic/update-success-stamp ]] ||\' |sudo tee -a /etc/profile.d/checkUpgrade.sh
echo '	 (( ( $(date +%s) - $(stat -c %Y /var/lib/apt/periodic/update-success-stamp) ) > $no_of_seconds )) ; then' |\
            sudo tee -a /etc/profile.d/checkUpgrade.sh > /dev/null
echo '  echo It has been at least $no_of_days days since the last update' |sudo tee -a /etc/profile.d/checkUpgrade.sh > /dev/null
echo '  echo Please run \"sudo apt-get update \&\& sudo apt-get -y upgrade\"' |\
                 sudo tee -a /etc/profile.d/checkUpgrade.sh > /dev/null
echo fi | sudo tee -a /etc/profile.d/checkUpgrade.sh > /dev/null


eLog "__ Updating _______________________________________________________"
eLog "About to fully upgrade all relevant packages and optionally install others"
eLog "This will take some time"

# In case the upgrade does nothing create the masrker file

sudo touch /var/lib/apt/periodic/update-success-stamp

# Make sure system is fully up to date
execLog sudo apt-get -y dist-upgrade

ask() {
  read -p "$1" -r < /dev/tty
  echo $REPLY
}

eLog "__ I2C & SPI ______________________________________________________"
# Install and enable i2c and SPI
execLog sudo apt-get -y install i2c-tools lm-sensors python-smbus
sudo sed /etc/modprobe.d/raspi-blacklist.conf \
  -i -e 's/^#blacklist spi-bcm2708/blacklist spi-bcm2708/' \
  -e 's/^#blacklist i2c-bcm2708/blacklist i2c-bcm2708/'

execLog sudo adduser $USER i2c

eLog "Installed support for I2C serial interface and LM sensors"
eLog "added $USER to the i2c group"

eLog "__ Dev Tools ______________________________________________________"
eLog "We will now install a few useful development tools (editors, source code control etc)."
execLog sudo apt-get -y install vim git git-gui git-doc git-svn subversion screen tmux ack-grep emacs locate python-setuptools
execLog sudo easy_install pip
execLog sudo pip install virtualenv virtualenvwrapper  

eLog ""


  cat <<EOF | sudo tee /boot/machine.local
#newhostname=raspberrypi  # Host for /etc/host
#wifihostname=wfipi   # Hostname for wifi interface
#wifiSSID=wifipi-ap
#wifipsk=secretpsk
#wifi_ap_network=16 #  01-254
#interface=wlan0
#channel=6
#driver=hostpad
#
EOF

  cat <<'EOF' | sudo tee /usr/local/sbin/start-wifi-ap
#!/bin/sh

if [ -f /boot/machine.local ] ; then
  . /boot/machine.local # dash does not support `source` keyword
  oldhostname=$(cat /etc/hostname)
  if [ -n "$newhostname" -a "$hostname" != "$(cat /etc/hostname)"] ; then
    sudo hostname $newhostname
    sudo sed -ie 's/^\(..*\)'$oldhostname'\(.*\)$/\1'$newhostname'\2/' /etc/hosts
    sudo /etc/init.d/network restart
    logger "Changed hostname to $(hostname) on $interface"
  fi
  #todo Add wifihostname to interface
else
  network=01
  wifihostname=$(hostname)
  channel_number=6
  driver=hostpad
fi

EOF

eLog "__ Baracuda Copy Cloud ____________________________________________"
eLog "The Baracuda Copy Cloud storage service works nativly on the Pi."
if [[ $(ask "Do you wish to install and configure the Copy client? (http://copy.com/)[y/N] ") =~ ^[Yy]$ ]]
then
  execLog bash <(wget --no-check-certificate -O - https://copy.com/YJYNOLByOoYpmgRy)
  eLog "Baracuda installed"
else
  eLog "Operation not performed."
fi

eLog "__ Freetronics Pileven ____________________________________________"
if [[ $(ask "Do you wish to install support for the Freetronics Pileven board?[y/N] ") =~ ^[Yy]$ ]]
then
  execLog wget -O - https://github.com/freetronics/PiLeven-tools/releases/download/v1.0/install_pileven.sh | sudo bash
  eLog "Pileven installed"
else
  eLog "Operation not performed."
fi

eLog "__ Wiring Pi ______________________________________________________"
if [[ $(ask "Do you wish to install the Wiring Pi library? (http://wiringpi.com/)[y/N] ") =~ ^[Yy]$ ]]
then

  # Install the WiringPi

  WP=/usr/src/wiringPi

  sudo mkdir -p $WP
  sudo chown $USER:$(id -g -n $USER) $WP

  pushd $WP

  execLog git clone git://git.drogon.net/wiringPi .
  execLog ./build

  cat <<EOF |sudo tee /usr/local/bin/updateWiringPi
#!/usr/bin/env sh
# Keep wiringPi updated

cd $WP
git pull origin &&
./build &&
echo WiringPi updated ||
echo WiringPi update failed
EOF

  sudo chmod + /usr/local/bin/updateWiringPi

  eLog "To update the wiringPi library run the script /usr/local/bin/updateWiringPi as needed"
  eLog

  popd
  eLog "WiringPi installed."
else
  eLog "Operation not performed."
fi

eLog "__ Robot OS _______________________________________________________"
if [[ $(ask "Do you wish to install the Robot OS? (http://ros.org)[y/N] ") =~ ^[Yy]$ ]]
then
  # Add repo for Robot operating System
  echo "deb http://packages.ros.org/ros/ubuntu wheezy main" | sudo tee /etc/apt/sources.list.d/ros-latest.list
  execLog wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  execLog sudo apt-get update
  
  # from http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Indigo%20on%20Raspberry%20Pi#Installation

  # sudo apt-get -y install ros-groovy-ros-comm \
  #  ros-groovy-rqt-gui ros-groovy-rqt-common-plugins \
  #  ros-groovy-roscpp-tutorials ros-groovy-turtlesim \
  #  ros-groovy-rosserial-arduino 


  execLog sudo pip install -U rosdep rosinstall_generator wstool rosinstall
  execLog sudo rosdep init
  execLog rosdep update
  
  mkdir ~/ros_catkin_ws
  cd ~/ros_catkin_ws
  
  rosinstall_generator ros_comm --rosdistro indigo --deps --wet-only --exclude roslisp --tar > indigo-ros_comm-wet.rosinstall
  wstool init -j8 src indigo-ros_comm-wet.rosinstall
  # rosinstall_generator desktop --rosdistro indigo --deps --wet-only --exclude roslisp --tar > indigo-desktop-wet.rosinstall
  # wstool init -j8 src indigo-desktop-wet.rosinstall
  
  mkdir ~/ros_catkin_ws/external_src
  execLog sudo apt-get install -y checkinstall cmake
  
  # libconsole-bridge-dev
  eLog 'When check-install asks for any changes, the name (2) needs to change from'
  eLog 'console-bridge" to "libconsole-bridge-dev" otherwise the rosdep install wont find it.'
  cd ~/ros_catkin_ws/external_src
  execLog sudo apt-get install -y libboost-system-dev libboost-thread-dev
  execLog git clone https://github.com/ros/console_bridge.git
  cd console_bridge
  execLog cmake .
  execLog sudo checkinstall make install 
  
  # liblz4-dev
  cd ~/ros_catkin_ws/external_src
  wget http://archive.raspbian.org/raspbian/pool/main/l/lz4/liblz4-1_0.0~r122-2_armhf.deb
  wget http://archive.raspbian.org/raspbian/pool/main/l/lz4/liblz4-dev_0.0~r122-2_armhf.deb
  execLog sudo dpkg -i liblz4-1_0.0~r122-2_armhf.deb liblz4-dev_0.0~r122-2_armhf.deb

  # liburdfdom-headers-dev
  eLog  'When check-install asks for any changes, the name (2) needs to change from'
  eLog  '"urdfdom-headers" to "liburdfdom-headers-dev" otherwise the rosdep install wont find it.'
  cd ~/ros_catkin_ws/external_src
  execLog git clone https://github.com/ros/urdfdom_headers.git
  cd urdfdom_headers
  execLog cmake .
  execLog sudo checkinstall make install
  
  # liburdfdom-dev
  eLog 'When check-install asks for any changes, the name (2) needs to change from'
  eLog '"urdfdom" to "liburdfdom-dev" otherwise the rosdep install wont find it.'
  cd ~/ros_catkin_ws/external_src
  execLog sudo apt-get install libboost-test-dev libtinyxml-dev
  execLog git clone https://github.com/ros/urdfdom.git
  cd urdfdom
  execLog cmake .
  execLog sudo checkinstall make install
  
  # collada-dom-dev
  eLog 'When check-install asks for any changes, the name (2) needs to change from'
  eLog '"collada-dom" to "collada-dom-dev" otherwise the rosdep install wont find it.'
  cd ~/ros_catkin_ws/external_src
  execLog sudo apt-get install libboost-filesystem-dev libxml2-dev
  execLog wget http://downloads.sourceforge.net/project/collada-dom/Collada%20DOM/Collada%20DOM%202.4/collada-dom-2.4.0.tgz
  tar -xzf collada-dom-2.4.0.tgz
  cd collada-dom-2.4.0
  execLog cmake .
  execLog sudo checkinstall make install
  
  cd ~/ros_catkin_ws
  rosdep install --from-paths src --ignore-src --rosdistro indigo -y -r --os=debian:wheezy
  execLog sudo ./src/catkin/bin/catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --install-space /opt/ros/indigo
  
  echo '# Setup for ROS ' |sudo tee /etc/profile.d/ros.sh
  echo source /opt/ros/indigo/setup.bash |sudo tee -a  /etc/profile.d/ros.sh
  eLog "RobotOS installed."
else
  eLog "Operation not performed."
fi

eLog "__ JDK 8 __________________________________________________________"
if [[ $(ask "Do you wish to install a Java Development Kit?[y/N] ") =~ ^[Yy]$ ]] ; then
  execLog sudo apt-get -y install oracle-java8-jdk
  eLog "JDK installed."
else
  eLog "Operation not performed."
fi

eLog "__ Arduino IDE ____________________________________________________"
if [[ $(ask "Do you wish to install the Arduino IDE (NB Will install JDK if needed)? [y/N] ") =~ ^[Yy]$ ]] ; then
  execLog sudo apt-get -y install oracle-java8-jdk arduino arduino-mk libdevice-serialport-perl
  eLog "Arduino IDE installed."
else
  eLog "Operation not performed."
fi

eLog "__ Node.js ________________________________________________________"
if [[ $(ask "Do you wish to install node.js etc for NodeBot dev? (NB Will install JDK if needed)? [y/N] ") =~ ^[Yy]$ ]]
then
  execLog sudo apt-get -y install oracle-java8-jdk minicom arduino arduino-mk libdevice-serialport-perl
  execLog sudo pip install ino

  wget https://node-arm.herokuapp.com/node_latest_armhf.deb
  execLog sudo dpkg -i node_latest_armhf.deb
  rm node_latest_armhf.deb
  eLog "Node.js installed."
else
  eLog "Operation not performed."
fi

eLog "__ Cleanup ________________________________________________________"
# Remove anything out of date
execLog sudo apt-get autoremove
# Save a few hundred Mb of disk space by removing downloaded deb archives
execLog sudo apt-get clean

# Stop raspi-config from running on next reboot

[[ -e /etc/profile.d/raspi-config.sh ]] && sudo rm -f /etc/profile.d/raspi-config.sh

eLog "Please use sudo raspi-config to configure additional options and"
eLog "use sudo apt-get dist-upgrade on a regular basis"
read -p "System will reboot in 5 seconds. Press any key to continue" -n 1 -r < /dev/tty

execLog nohup bash -c 'sleep 5; sudo shutdown -rF now'& # Force disk check
