#!/usr/bin/env bash
# Copyright (c) 2013 All Right Reserved  Alec Clews
#
# author: Alec Clews
# alecclews@gmail.com
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#
#    Special thanks to @mikered for wifi set up code

echo
echo About to fully upgrade all relevent packges and optionally install others
echo This will take some time
echo


# Make sure system is fully up to date
sudo apt-get -y dist-upgrade

ask() {
  read -p "$1" -r < /dev/tty
  echo $REPLY
}

# Install and enable i2c and SPI
sudo apt-get -y install i2c-tools lm-sensors python-smbus
sudo sed /etc/modprobe.d/raspi-blacklist.conf \
  -i -e 's/^#blacklist spi-bcm2708/blacklist spi-bcm2708/' \
  -e 's/^#blacklist i2c-bcm2708/blacklist i2c-bcm2708/'

sudo adduser $USER i2c

echo Installed support for I2C serial interface and LM sensors
echo added $USER to the i2c group
echo

# Install a few dev tools
sudo apt-get -y install vim git git-gui git-doc git-svn subversion screen tmux ack-grep emacs locate


# Install the WiringPi

WP=/usr/src/wiringPi

sudo mkdir -p $WP
sudo chown $USER:$(id -g -n $USER) $WP

cd $WP

git clone git://git.drogon.net/wiringPi .
./build

cat <<EOF |sudo tee /usr/local/bin/updateWiringPi
#!/usr/bin/env sh
# Keep wiringPi updated

cd $WP
git pull origin &&
./build &&
echo WiringPi updated ||
echo WiringPi update failed
EOF

sudo chmod + /usr/local/bin/updateWiringPi

echo "To update the wiringPi library run the script /usr/local/bin/updateWiringPi as needed"
echo


if [[ $(ask "Do you wish to install the Robot OS? (http://ros.org)[y/N] ") =~ ^[Yy]$ ]]
then
  # Add repo for Robot operating System
  sudo sh -c 'echo \
    "deb http://64.91.227.57/repos/rospbian wheezy main" > \
  /etc/apt/sources.list.d/rospbian.list'
  wget http://64.91.227.57/repos/rospbian.key -O - | sudo apt-key add -


  sudo apt-get -y install ros-groovy-ros-comm \
    ros-groovy-rqt-gui ros-groovy-rqt-common-plugins \
    ros-groovy-roscpp-tutorials ros-groovy-turtlesim \
    ros-groovy-rosserial-arduino 

  echo '# Setup for ROS ' |sudo tee -a /etc/profile
  echo source /opt/ros/groovy/setup.bash |sudo tee -a  /etc/profile
else
  echo
fi

read -p  "Do you wish to install a JDK?" -n 1 -r  < /dev/tty
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
        sudo apt-get -y install oracle-java7-jdk oracle-java7-doc
fi

read -p  "Do you wish to install the Arduino IDE (NB Will install JDK if needed) ? " -n 1 -r  < /dev/tty
echo

if [[ $REPLY =~ ^[Yy]$ ]] ; then
        sudo apt-get -y install oracle-java7-jdk arduino arduino-mk libdevice-serialport-perl
fi

read -p  "Do you wish to install the NodBots (NB Will install Arduino and OpenJDK if needed) ? " -n 1 -r  < /dev/tty
echo

if [[ $REPLY =~ ^[Yy]$ ]] ; then

  sudo apt-get -y install oracle-java7-jdk
  sudo apt-get -y install minicom arduino arduino-mk libdevice-serialport-perl

  node_ver=v0.10.17   # Modify to lastest that works
  wget http://nodejs.org/dist/$node_ver/node-$node_ver-linux-arm-pi.tar.gz
  [[ -d /opt/node-$node_ver-linux-arm-pi ]] && sudo rm -rf /opt/node-$node_ver-linux-arm-pi
  sudo tar -zxpf node-$node_ver-linux-arm-pi.tar.gz -C /opt
  [[ -L /opt/node ]] && sudo rm /opt/node
  sudo ln -s /opt/node-$node_ver-linux-arm-pi /opt/node

  echo 'NODE_JS_HOME=/opt/node; export NODE_JS_HOME' |sudo tee -a /etc/profile
  echo 'PATH=$PATH:$NODE_JS_HOME/bin' |sudo tee -a /etc/profile

  export NODE_JS_HOME=/opt/node
  PATH=$PATH:$NODE_JS_HOME/bin

  sudo -i npm install -g serialport   # 1.1.3
  sudo -i npm install -g firmata      # 0.2.9
  sudo -i npm install -g johnny-five  # 0.7.2
  sudo -i npm install -g socket.io    # 0.9.16

fi

# Remove anything out of date
sudo apt-get autoremove
# Save a few hundred Mb of disk space by removing downloaded deb archives
sudo apt-get clean

# Stop raspi-config from running on next reboot

[[ -e /etc/profile.d/raspi-config.sh ]] && sudo rm -f /etc/profile.d/raspi-config.sh

echo Please use sudo raspi-config to configure additional options and use sudo apt-get dist-upgrade on a regular basis

read -p "System will now reboot. Press any key to continue " -n 1 -r < /dev/tty

sudo shutdown -rF now # Force disk check
